### ISSUE TITLE
java.lang.NoClassDefFoundError: Failed resolution of: Ljava/lang/management/ManagementFactory;

### ISSUE THREAD

**Issue by Miger88** [oberasoftware/jasdb#18]
Hello,  
I try to write a small java class for managing all access to the database, named JASDBManager.java  .
Inside my constructor I got the following error:

09-01 09:01:52.326 30109-30109/com.example.michael.dbmanager_debug_application E/AndroidRuntime: FATAL EXCEPTION: main
                                                                                                 Process: com.example.michael.dbmanager_debug_application, PID: 30109
                                                                                                 java.lang.IllegalStateException: Could not execute method for android:onClick
                                                                                                     at android.view.View$DeclaredOnClickListener.onClick(View.java:4455)
                                                                                                     at android.view.View.performClick(View.java:5201)
                                                                                                     at android.view.View$PerformClick.run(View.java:21209)
                                                                                                     at android.os.Handler.handleCallback(Handler.java:739)
                                                                                                     at android.os.Handler.dispatchMessage(Handler.java:95)
                                                                                                     at android.os.Looper.loop(Looper.java:148)
                                                                                                     at android.app.ActivityThread.main(ActivityThread.java:5525)
                                                                                                     at java.lang.reflect.Method.invoke(Native Method)
                                                                                                     at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:730)
                                                                                                     at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:620)
                                                                                                  Caused by: java.lang.reflect.InvocationTargetException
                                                                                                     at java.lang.reflect.Method.invoke(Native Method)
                                                                                                     at android.view.View$DeclaredOnClickListener.onClick(View.java:4450)
                                                                                                     at android.view.View.performClick(View.java:5201) 
                                                                                                     at android.view.View$PerformClick.run(View.java:21209) 
                                                                                                     at android.os.Handler.handleCallback(Handler.java:739) 
                                                                                                     at android.os.Handler.dispatchMessage(Handler.java:95) 
                                                                                                     at android.os.Looper.loop(Looper.java:148) 
                                                                                                     at android.app.ActivityThread.main(ActivityThread.java:5525) 
                                                                                                     at java.lang.reflect.Method.invoke(Native Method) 
                                                                                                     at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:730) 
                                                                                                     at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:620) 
                                                                                                  **Caused by: java.lang.NoClassDefFoundError: Failed resolution of: Ljava/lang/management/ManagementFactory;**
                                                                                                     at nl.renarj.jasdb.core.platform.HotspotPlatformManager.getProcessId(Unknown)
                                                                                                     at nl.renarj.jasdb.core.SimpleKernel.<init>(Unknown)
                                                                                                     at nl.renarj.jasdb.core.SimpleKernel.loadKernel(Unknown)
                                                                                                     at nl.renarj.jasdb.core.SimpleKernel.getInstance(Unknown)
                                                                                                     at nl.renarj.jasdb.core.SimpleKernel.getInstanceFactory(Unknown)
                                                                                                     at nl.renarj.jasdb.LocalDBSession.<init>(Unknown)
                                                                                                     at com.example.michael.dbmanager_debug_application.JASDBManager.<init>(JASDBManager.java:24)
                                                                                                     at com.example.michael.dbmanager_debug_application.MainActivity.debugJASDB(MainActivity.java:55)
                                                                                                     at com.example.michael.dbmanager_debug_application.MainActivity.debug(MainActivity.java:37)
                                                                                                     at java.lang.reflect.Method.invoke(Native Method) 
                                                                                                     at android.view.View$DeclaredOnClickListener.onClick(View.java:4450) 
                                                                                                     at android.view.View.performClick(View.java:5201) 
                                                                                                     at android.view.View$PerformClick.run(View.java:21209) 
                                                                                                     at android.os.Handler.handleCallback(Handler.java:739) 
                                                                                                     at android.os.Handler.dispatchMessage(Handler.java:95) 
                                                                                                     at android.os.Looper.loop(Looper.java:148) 
                                                                                                     at android.app.ActivityThread.main(ActivityThread.java:5525) 
                                                                                                     at java.lang.reflect.Method.invoke(Native Method) 
                                                                                                     at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:730) 
                                                                                                     at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:620) 
                                                                                                  **Caused by: java.lang.ClassNotFoundException: Didn't find class "java.lang.management.ManagementFactory" on path: DexPathList[[zip file "/data/app/com.example.michael.dbmanager_debug_application-2/base.apk"],nativeLibraryDirectories=[/data/app/com.example.michael.dbmanager_debug_application-2/lib/arm64, /vendor/lib64, /system/lib64]]**
                                                                                                     at dalvik.system.BaseDexClassLoader.findClass(BaseDexClassLoader.java:56)
                                                                                                     at java.lang.ClassLoader.loadClass(ClassLoader.java:511)
                                                                                                     at java.lang.ClassLoader.loadClass(ClassLoader.java:469)
                                                                                                     at nl.renarj.jasdb.core.platform.HotspotPlatformManager.getProcessId(Unknown) 
                                                                                                     at nl.renarj.jasdb.core.SimpleKernel.<init>(Unknown) 
                                                                                                     at nl.renarj.jasdb.core.SimpleKernel.loadKernel(Unknown) 
                                                                                                     at nl.renarj.jasdb.core.SimpleKernel.getInstance(Unknown) 
                                                                                                     at nl.renarj.jasdb.core.SimpleKernel.getInstanceFactory(Unknown) 
                                                                                                     at nl.renarj.jasdb.LocalDBSession.<init>(Unknown) 
                                                                                                     at com.example.michael.dbmanager_debug_application.JASDBManager.<init>(JASDBManager.java:24) 
                                                                                                     at com.example.michael.dbmanager_debug_application.MainActivity.debugJASDB(MainActivity.java:55) 
                                                                                                     at com.example.michael.dbmanager_debug_application.MainActivity.debug(MainActivity.java:37) 
                                                                                                     at java.lang.reflect.Method.invoke(Native Method) 
                                                                                                     at android.view.View$DeclaredOnClickListener.onClick(View.java:4450) 
                                                                                                     at android.view.View.performClick(View.java:5201) 
                                                                                                     at android.view.View$PerformClick.run(View.java:21209) 
                                                                                                     at android.os.Handler.handleCallback(Handler.java:739) 
                                                                                                     at android.os.Handler.dispatchMessage(Handler.java:95) 
                                                                                                     at android.os.Looper.loop(Looper.java:148) 
                                                                                                     at android.app.ActivityThread.main(ActivityThread.java:5525) 
                                                                                                     at java.lang.reflect.Method.invoke(Native Method) 
                                                                                                     at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:730) 
                                                                                                     at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:620) 
                                                                                                 	Suppressed: java.lang.ClassNotFoundException: java.lang.management.ManagementFactory
                                                                                                     at java.lang.Class.classForName(Native Method)
                                                                                                     at java.lang.BootClassLoader.findClass(ClassLoader.java:781)
                                                                                                     at java.lang.BootClassLoader.loadClass(ClassLoader.java:841)
                                                                                                     at java.lang.ClassLoader.loadClass(ClassLoader.java:504)
                                                                                                     		... 21 more
                                                                                                  Caused by: java.lang.NoClassDefFoundError: Class not found using the boot class loader; no stack trace available

My JASDBManager class is the following:

[JASDBManager.txt](https://github.com/oberasoftware/jasdb/files/449010/JASDBManager.txt)

Can you help me again?

**Comment by renarj** [comment]
This is because on Android devices you need to use a AndroidDBSession object. 

This should do the trick, instead of LocalDBSession:
```
DBSession session = new AndroidDBSession(getApplicationContext());
```

**Comment by Miger88** [comment]
I changed my JASDBManager.java
[JASDBManager.txt](https://github.com/oberasoftware/jasdb/files/451483/JASDBManager.txt)


But I got still  the  same error.
You can see the whole Logcat in attached file. 
[JASDBManager Logcat.txt](https://github.com/oberasoftware/jasdb/files/451480/JASDBManager.Logcat.txt)

Any other Idea?

**Comment by renarj** [comment]
It seems the issue is different this time, you can see this exception:
```
Caused by: java.lang.NoClassDefFoundError: java.util.Optional
					   at libcore.reflect.InternalNames.getClass(InternalNames.java:55)
					   at java.lang.Class.getDexCacheType(Class.java:476)
					   at java.lang.reflect.Method.getReturnType(Method.java:183)
					   at java.lang.Class.getDeclaredMethods(Class.java:672)
```

This is due to the fact that java.util.Optional is a Java 8 specific class, and only is added in Android since API level 24: https://developer.android.com/reference/java/util/Optional.html

So for the moment the only solution is to make sure you target Android APi level 24 for your project.

**Comment by Miger88** [comment]
I am sure that I target Android APi 24, but I still got errors.

[JASDB Errors.txt](https://github.com/oberasoftware/jasdb/files/469247/JASDB.Errors.txt)

[JASDB Module Build File.txt](https://github.com/oberasoftware/jasdb/files/469250/JASDB.Module.Build.File.txt)

**Comment by AmeliaPessoa** [comment]
I have the same error also using API 24.

**Comment by Miger88** [comment]
I stopped working with jasdb for android because I couldn't fix this issue. I am sorry AmeliaPessoa, I can't help you with this issue. 

I worked with jasdb only in the content of my master study one year ago.

**Comment by brunocasamassa** [comment]
i got the same error but using mongodb instead:
Failed to get process identifier from JMX, using random number instead
                                                                                        java.lang.NoClassDefFoundError: Failed resolution of: Ljava/lang/management/ManagementFactory;
                                                                                            at org.bson.types.ObjectId.createProcessIdentifier(ObjectId.java:506)


someone knows how to fixx it??

**Comment by Weian-wang** [comment]
Chinese？
